name: Deploy delivery service

on:
  push:
    paths-ignore:
      - ".github/workflows/deploy.yml"
      - ".github/workflows/build-tugboat.yml"
      # Changes to tugoboat should not change the delivery service
      - "tugboat/**"
    # See "if:" below
    # branches:
    #   - main

jobs:
  build:
    # There is currently no way to combine event triggers "if branch is main AND file is changed"
    if: github.ref_name == 'main'
    uses: ./.github/workflows/build-docker.yml
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    with:
      target: final-delivery-service
      image_name: ${{ github.repository }}
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
